[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "SyMBac"
version = "0.5.0"
authors = [
    {name = "Georgeos Hardo", email = "gh464@cam.ac.uk"},
]
description = "A package for generating synthetic images of bacteria in phase contrast or fluorescence. Used for creating training data for machine learning segmentation and tracking algorithms."
readme = "README.md"
requires-python = ">=3.8"
license = {text = "GPL-2.0"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Image Processing",
    "Topic :: Scientific/Engineering"
]
dependencies = [
    "tifffile",
    "scikit-image",
    "matplotlib",
    "tqdm",
    "pandas",
    "natsort",
    "jupyterlab",
    "ipywidgets",
    "joblib",
    "scipy",
    "napari[all]",
    "pymunk",
    "pyglet",
    "matplotlib-scalebar",
    "psfmodels",
    "pandoc",
    "zarr",
    "numpy",
    "noise"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "flake8",
    "black",
    "isort",
    "pre-commit",
    "pip-tools"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"symbac" = ["sample_images/*.tiff"]

[project.urls]
"Homepage" = "https://github.com/georgeoshardo/SyMBac"
"Documentation" = "https://symbac.readthedocs.io/en/latest/"

[tool.black]
line-length = 100
target-version = ['py38']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.flake8]
max-line-length = 100
extend-ignore = "E203, W503"
exclude = [
    ".git",
    "__pycache__",
    "docs/source/conf.py",
    "old",
    "build",
    "dist",
    ".venv",
]
