# As a general rule, the latest release of Keras is compatible with the latest
# release of TensorFlow as well as the previous release of TensorFlow (in most
# cases, it is actually compatible with several prior TF releases, but that is
# not guaranteed).
#
# -- https://github.com/keras-team/keras/issues/10440#issuecomment-397428200

language: python

# branches:
#   only:
#     - master
#     - dev

env:
  - TENSORFLOW='tensorflow<2' EXTRA=''

matrix:
  include:
      # TF 1
    - os: linux
      python: 3.6
      env: TENSORFLOW='tensorflow<2' EXTRA='' INSTALL_FROM_SOURCE=1
    - os: linux
      python: 3.7
      env: TENSORFLOW='tensorflow<2' EXTRA='' INSTALL_FROM_SOURCE=1
      # TF 2
    - os: linux
      python: 3.6
      env: TENSORFLOW='tensorflow' EXTRA='' INSTALL_FROM_SOURCE=1
    - os: linux
      python: 3.7
      env: TENSORFLOW='tensorflow' EXTRA='' INSTALL_FROM_SOURCE=1
    - os: linux
      python: 3.8
      env: TENSORFLOW='tensorflow' EXTRA='' INSTALL_FROM_SOURCE=1
      #########################################################################
      ### additional tests in master: install from pypi
      # TF 1
    - os: linux
      python: 3.6
      if: branch = master
    - os: linux
      python: 3.7
      if: branch = master
      # TF 2
    - os: linux
      python: 3.6
      env: TENSORFLOW='tensorflow' EXTRA=''
      if: branch = master
    - os: linux
      python: 3.7
      env: TENSORFLOW='tensorflow' EXTRA=''
      if: branch = master
    - os: linux
      python: 3.8
      env: TENSORFLOW='tensorflow' EXTRA=''
      if: branch = master

install:
  - pip install $TENSORFLOW $EXTRA
  - if [[ -n $INSTALL_FROM_SOURCE ]]; then
       pip install .;
    else
       pip install stardist;
    fi;

script:
  - pytest -v --durations=50 -m "not gpu";